"""
Train the final CG force field (harmonic bonded prior + GNN correction) by
force matching against the reference trajectory generated by
`01_generate_reference_trajectory.py`. Produces the artifacts loaded by
notebooks/03_train_and_validate_cgnet.ipynb:

    data/cgnet_correction_state.pt
    data/prior_params.pt
    data/training_history_v2.npy
    data/cg_positions_nm.npy, data/cg_forces_kjmolnm.npy (the CG-mapped dataset itself)
    data/phi_psi_aa.npy, data/phi_psi_cg.npy (dihedral validation data)

Run from the project root:  python scripts/02_train_cgnet.py
"""
import sys
import time
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader, random_split

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from openmm.app import PDBFile, ForceField, NoCutoff, HBonds
from openmm import unit

from src.cg_mapping import map_to_cg, compute_backbone_dihedrals, BEAD_NAMES, BEAD_ATOM_GROUPS
from src.cg_gnn_model import CGSchNetLike, HarmonicBondPrior, CGForceField
from src.cg_dataset import ForceMatchingDataset, force_rms_scale

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
BONDED_PAIRS = [(0, 1), (1, 2), (2, 3), (3, 4)]


def build_cg_dataset():
    pdb = PDBFile(str(DATA_DIR / "alanine-dipeptide.pdb"))
    ff = ForceField("amber14-all.xml", "implicit/gbn2.xml")
    system = ff.createSystem(pdb.topology, nonbondedMethod=NoCutoff, constraints=HBonds)
    masses = np.array([system.getParticleMass(i).value_in_unit(unit.amu)
                        for i in range(system.getNumParticles())])

    positions = np.load(DATA_DIR / "aa_positions_nm.npy")
    forces = np.load(DATA_DIR / "aa_forces_kjmolnm.npy")

    cg_pos, cg_force = map_to_cg(positions, forces, masses)
    np.save(DATA_DIR / "cg_positions_nm.npy", cg_pos)
    np.save(DATA_DIR / "cg_forces_kjmolnm.npy", cg_force)

    aa_idx = {"C_ACE": 4, "N_ALA": 6, "CA_ALA": 8, "C_ALA": 14, "N_NME": 16}
    phi_aa, psi_aa = compute_backbone_dihedrals(positions, aa_idx)
    cg_idx = {name: i for i, name in enumerate(BEAD_NAMES)}
    phi_cg, psi_cg = compute_backbone_dihedrals(cg_pos, cg_idx)
    np.save(DATA_DIR / "phi_psi_aa.npy", np.stack([phi_aa, psi_aa], axis=1))
    np.save(DATA_DIR / "phi_psi_cg.npy", np.stack([phi_cg, psi_cg], axis=1))

    bead_masses = np.array([masses[idx].sum() for idx in BEAD_ATOM_GROUPS])
    return cg_pos, cg_force, bead_masses


def train(n_epochs: int = 60, batch_size: int = 256, lr: float = 1e-3, seed: int = 0):
    torch.manual_seed(seed)
    cg_pos, cg_force, bead_masses = build_cg_dataset()

    com = cg_pos.mean(axis=1, keepdims=True)
    cg_pos_centered = cg_pos - com
    rms_force = force_rms_scale(cg_force)

    pos_t = torch.as_tensor(cg_pos_centered, dtype=torch.float32)
    prior = HarmonicBondPrior.fit_from_data(pos_t, BONDED_PAIRS, temperature_k=300.0)

    dataset = ForceMatchingDataset(cg_pos_centered, cg_force)  # raw (physical) units
    n_val = int(0.1 * len(dataset))
    n_train = len(dataset) - n_val
    train_set, val_set = random_split(dataset, [n_train, n_val],
                                       generator=torch.Generator().manual_seed(seed))
    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=1024)

    correction = CGSchNetLike(n_beads=5, n_features=32, n_rbf=32, n_interactions=2, d_max=1.0)
    model = CGForceField(prior, correction)
    opt = torch.optim.Adam(correction.parameters(), lr=lr)
    sched = torch.optim.lr_scheduler.StepLR(opt, step_size=20, gamma=0.5)

    history = []
    t0 = time.time()
    for epoch in range(n_epochs):
        model.train()
        train_loss = 0.0
        for pos, force in train_loader:
            opt.zero_grad()
            _, pred_force = model(pos)
            loss = torch.mean((pred_force - force) ** 2)
            loss.backward()
            opt.step()
            train_loss += loss.item() * len(pos)
        train_loss /= n_train
        sched.step()

        model.eval()
        val_loss = 0.0
        for pos, force in val_loader:
            _, pred_force = model(pos)
            loss = torch.mean((pred_force - force) ** 2)
            val_loss += loss.item() * len(pos)
        val_loss /= n_val
        history.append((train_loss, val_loss))

        if epoch % 5 == 0 or epoch == n_epochs - 1:
            print(f"epoch {epoch}: train {train_loss/rms_force**2:.4f}  "
                  f"val {val_loss/rms_force**2:.4f} (normalized)  {time.time()-t0:.1f}s")

    torch.save(correction.state_dict(), DATA_DIR / "cgnet_correction_state.pt")
    torch.save({"d0": prior.d0, "k": prior.k}, DATA_DIR / "prior_params.pt")
    np.save(DATA_DIR / "training_history_v2.npy", np.array(history))
    print("done. artifacts written to", DATA_DIR)


if __name__ == "__main__":
    train()
