"""Compare the mapped reference conformational distribution with CG dynamics.

The mapped reference trajectory is the validation reference. The CG distribution
is generated by running the trained harmonic-prior + GNN force field, rather
than by comparing the reference trajectory to itself.
"""

from pathlib import Path
import sys

import numpy as np
import pandas as pd
import torch

BASE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BASE))

from src.cg_gnn_model import CGSchNetLike, HarmonicBondPrior, CGForceField
from src.cg_mapping import BEAD_NAMES, compute_backbone_dihedrals
from src.cg_dynamics import run_langevin
from src.conformational_metrics import conformational_js_divergence

DATA_DIR = BASE / "data"
RESULTS_DIR = BASE / "results"

BONDED_PAIRS = [(0, 1), (1, 2), (2, 3), (3, 4)]
BEAD_MASSES_AMU = np.array([43.044, 15.018, 28.052, 28.010, 30.052])
N_BINS = 36
N_STEPS = 100_000
SAVE_EVERY = 20
BURN_IN_FRAMES = 300
SEEDS = (1, 2, 3)


def build_trained_model():
    cg_positions = np.load(DATA_DIR / "cg_positions_nm.npy")
    centered = cg_positions - cg_positions.mean(axis=1, keepdims=True)

    prior_params = torch.load(
        DATA_DIR / "prior_params.pt",
        map_location="cpu",
        weights_only=True,
    )
    prior = HarmonicBondPrior(
        BONDED_PAIRS,
        d0=prior_params["d0"],
        k=prior_params["k"],
    )

    correction = CGSchNetLike(
        n_beads=5,
        n_features=32,
        n_rbf=32,
        n_interactions=2,
        d_max=1.0,
    )
    correction.load_state_dict(
        torch.load(
            DATA_DIR / "cgnet_correction_state.pt",
            map_location="cpu",
            weights_only=True,
        )
    )
    model = CGForceField(prior, correction)
    model.eval()

    return model, centered[0]


def generate_cg_dihedrals():
    model, start = build_trained_model()
    cg_idx = {name: i for i, name in enumerate(BEAD_NAMES)}

    all_dihedrals = []
    position_ranges = []

    for seed in SEEDS:
        traj = run_langevin(
            model,
            start,
            BEAD_MASSES_AMU,
            n_steps=N_STEPS,
            timestep_ps=0.002,
            temperature_k=300.0,
            friction_per_ps=1.0,
            save_every=SAVE_EVERY,
            seed=seed,
        )
        traj_centered = traj - traj.mean(axis=1, keepdims=True)
        traj_eq = traj_centered[BURN_IN_FRAMES:]
        phi, psi = compute_backbone_dihedrals(traj_eq, cg_idx)
        all_dihedrals.append(np.stack([phi, psi], axis=1))
        position_ranges.append((traj_centered.min(), traj_centered.max()))

    return np.concatenate(all_dihedrals, axis=0), position_ranges


def main():
    phi_psi_ref = np.load(DATA_DIR / "phi_psi_cg.npy")

    phi_psi_dynamics, position_ranges = generate_cg_dihedrals()
    RESULTS_DIR.mkdir(exist_ok=True)

    np.save(
        DATA_DIR / "phi_psi_cg_dynamics.npy",
        phi_psi_dynamics,
    )

    dynamics_jsd = conformational_js_divergence(
        phi_psi_ref, phi_psi_dynamics
    )

    midpoint = len(phi_psi_ref) // 2
    reference_half_jsd = conformational_js_divergence(
        phi_psi_ref[:midpoint],
        phi_psi_ref[midpoint:],
    )

    # A smaller, independent reference-vs-reference comparison makes the
    # finite-sample effect more comparable to the size of a single CG run.
    rng = np.random.default_rng(0)
    idx_a = rng.choice(len(phi_psi_ref), size=1700, replace=False)
    remaining = np.setdiff1d(np.arange(len(phi_psi_ref)), idx_a)
    idx_b = rng.choice(remaining, size=1700, replace=False)
    subsample_jsd = conformational_js_divergence(
        phi_psi_ref[idx_a],
        phi_psi_ref[idx_b],
    )

    pd.DataFrame(
        [
            {
                "metric": "CG dynamics vs mapped reference JSD",
                "value_bits": dynamics_jsd,
                "n_bins_per_angle": N_BINS,
                "reference_samples": len(phi_psi_ref),
                "cg_dynamics_samples": len(phi_psi_dynamics),
                "reference_half_jsd_bits": reference_half_jsd,
                "reference_1700_vs_1700_jsd_bits": subsample_jsd,
                "n_steps_per_seed": N_STEPS,
                "n_seeds": len(SEEDS),
            }
        ]
    ).to_csv(
        RESULTS_DIR / "conformational_distribution_comparison.csv",
        index=False,
    )

    print("=== Mapped reference vs CG dynamics ===")
    print(f"CG-dynamics JSD: {dynamics_jsd:.4f} bits")
    print(f"Reference half-vs-half JSD: {reference_half_jsd:.4f} bits")
    print(f"Reference 1700-vs-1700 JSD: {subsample_jsd:.4f} bits")
    print(f"Reference samples: {len(phi_psi_ref)}")
    print(f"CG-dynamics samples: {len(phi_psi_dynamics)}")
    print(f"Seeds: {SEEDS}")
    print(f"Steps per seed: {N_STEPS}")
    print(
        "Position ranges by seed: "
        + ", ".join(f"{lo:.3f} to {hi:.3f} nm" for lo, hi in position_ranges)
    )
    print(
        f"Saved dynamics dihedrals: "
        f"{DATA_DIR / 'phi_psi_cg_dynamics.npy'}"
    )
    print(
        f"Saved comparison: "
        f"{RESULTS_DIR / 'conformational_distribution_comparison.csv'}"
    )


if __name__ == "__main__":
    main()
